name: CodeCov

on: [push, pull_request]

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@main
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate Report
        run: |
          pip install coverage
          cd tests
          coverage run engine.py
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          fail_ci_if_error: true
          files: ./coverage.xml