name: CodeCov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Generate report
      run: |
        pip install coverage
        cd tests
        coverage run engine.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      run: echo ${{ secrets.CODECOV_TOKEN }} 
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml,
        name: codecov-umbrella
        verbose: true